[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/chi-siamo"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/cart"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/account"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ordine-confermato"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/cart"
  [headers.values]
    X-Robots-Tag = "noindex, follow"

[[headers]]
  for = "/account"
  [headers.values]
    X-Robots-Tag = "noindex, follow"

[[headers]]
  for = "/search"
  [headers.values]
    X-Robots-Tag = "noindex, follow"

[[headers]]
  for = "/ordine-confermato"
  [headers.values]
    X-Robots-Tag = "noindex, follow"
